export class Locations {
  public all_locations: any = [
    {
      value: "1",
      country_id: "1",
      state_id: "2",
      label: "Acacia Avenues",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "2",
      country_id: "1",
      state_id: "2",
      label: "Academic City",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "3",
      country_id: "1",
      state_id: "2",
      label: "Akoya (DAMAC Hills)",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "4",
      country_id: "1",
      state_id: "2",
      label: "Akoya Oxygen",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "5",
      country_id: "1",
      state_id: "2",
      label: "Al Awir",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "6",
      country_id: "1",
      state_id: "2",
      label: "Al Badaa",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "7",
      country_id: "1",
      state_id: "2",
      label: "Al Barari",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "8",
      country_id: "1",
      state_id: "2",
      label: "Al Barsha",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "9",
      country_id: "1",
      state_id: "2",
      label: "Al Furjan",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "10",
      country_id: "1",
      state_id: "2",
      label: "Al Garhoud",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "11",
      country_id: "1",
      state_id: "2",
      label: "Al Hamriya",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "12",
      country_id: "1",
      state_id: "2",
      label: "Al Jaddaf",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "13",
      country_id: "1",
      state_id: "2",
      label: "Al Jafiliya",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "14",
      country_id: "1",
      state_id: "2",
      label: "Al Karama",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "15",
      country_id: "1",
      state_id: "2",
      label: "Al Khail Heights",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "16",
      country_id: "1",
      state_id: "2",
      label: "Al Khawaneej",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "17",
      country_id: "1",
      state_id: "2",
      label: "Al Kifaf",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "18",
      country_id: "1",
      state_id: "2",
      label: "Al Mamzar",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "19",
      country_id: "1",
      state_id: "2",
      label: "Al Manara",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "20",
      country_id: "1",
      state_id: "2",
      label: "Al Mina",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "21",
      country_id: "1",
      state_id: "2",
      label: "Al Mizhar",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "22",
      country_id: "1",
      state_id: "2",
      label: "Al Nahda",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "23",
      country_id: "1",
      state_id: "2",
      label: "Al Nahda 1",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "24",
      country_id: "1",
      state_id: "2",
      label: "Al Nahda 2",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "25",
      country_id: "1",
      state_id: "2",
      label: "Al Quoz",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "26",
      country_id: "1",
      state_id: "2",
      label: "Al Qusais",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "27",
      country_id: "1",
      state_id: "2",
      label: "Al Rashidiya",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "28",
      country_id: "1",
      state_id: "2",
      label: "Al Rashidiya",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "29",
      country_id: "1",
      state_id: "2",
      label: "Al Rigga",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "30",
      country_id: "1",
      state_id: "2",
      label: "Al Safa",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "31",
      country_id: "1",
      state_id: "2",
      label: "Al Sufouh",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "32",
      country_id: "1",
      state_id: "2",
      label: "Al Twar",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "33",
      country_id: "1",
      state_id: "2",
      label: "Al Warqaa",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "34",
      country_id: "1",
      state_id: "2",
      label: "Al Warsan",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "35",
      country_id: "1",
      state_id: "2",
      label: "Al Wasl",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "36",
      country_id: "1",
      state_id: "2",
      label: "Arabian Ranches",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "37",
      country_id: "1",
      state_id: "2",
      label: "Arabian Ranches 2",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "38",
      country_id: "1",
      state_id: "2",
      label: "Arabian Ranches 3",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "39",
      country_id: "1",
      state_id: "2",
      label: "Arjan",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "40",
      country_id: "1",
      state_id: "2",
      label: "Barsha Heights(Tecom)",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "41",
      country_id: "1",
      state_id: "2",
      label: "Bawadi",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "42",
      country_id: "1",
      state_id: "2",
      label: "Bluewaters Island",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "43",
      country_id: "1",
      state_id: "2",
      label: "Bur Dubai",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "44",
      country_id: "1",
      state_id: "2",
      label: "Business Bay",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "45",
      country_id: "1",
      state_id: "2",
      label: "City Walk",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "46",
      country_id: "1",
      state_id: "2",
      label: "Culture Village",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "47",
      country_id: "1",
      state_id: "2",
      label: "Deira",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "48",
      country_id: "1",
      state_id: "2",
      label: "DIFC",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "49",
      country_id: "1",
      state_id: "2",
      label: "Discovery Gardens",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "50",
      country_id: "1",
      state_id: "2",
      label: "Downtown Dubai",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "51",
      country_id: "1",
      state_id: "2",
      label: "Downtown Jebel Ali",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "52",
      country_id: "1",
      state_id: "2",
      label: "Dubai Airport Freezone",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "53",
      country_id: "1",
      state_id: "2",
      label: "Dubai Airport Freezone(DAFZA)",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "54",
      country_id: "1",
      state_id: "2",
      label: "Dubai Creek Club Residences",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "55",
      country_id: "1",
      state_id: "2",
      label: "Dubai Creek Harbour",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "56",
      country_id: "1",
      state_id: "2",
      label: "Dubai Design District",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "57",
      country_id: "1",
      state_id: "2",
      label: "Dubai Festival City",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "58",
      country_id: "1",
      state_id: "2",
      label: "Dubai Harbour",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "59",
      country_id: "1",
      state_id: "2",
      label: "Dubai Healthcare City (DHCC)",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "60",
      country_id: "1",
      state_id: "2",
      label: "Dubai Hills Estate",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "61",
      country_id: "1",
      state_id: "2",
      label: "Dubai Industrial City",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "62",
      country_id: "1",
      state_id: "2",
      label: "Dubai Internet City",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "63",
      country_id: "1",
      state_id: "2",
      label: "Dubai Investment Park",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "64",
      country_id: "1",
      state_id: "2",
      label: "Dubai Lifestyle City",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "65",
      country_id: "1",
      state_id: "2",
      label: "Dubai Marina",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "66",
      country_id: "1",
      state_id: "2",
      label: "Dubai Maritime City",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "67",
      country_id: "1",
      state_id: "2",
      label: "Dubai Media City",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "68",
      country_id: "1",
      state_id: "2",
      label: "Dubai Pearl",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "69",
      country_id: "1",
      state_id: "2",
      label: "Dubai Science Park",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "70",
      country_id: "1",
      state_id: "2",
      label: "Dubai South City",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "71",
      country_id: "1",
      state_id: "2",
      label: "Dubai Studio City",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "72",
      country_id: "1",
      state_id: "2",
      label: "Dubai Waterfront",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "73",
      country_id: "1",
      state_id: "2",
      label: "Dubai World Central",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "74",
      country_id: "1",
      state_id: "2",
      label: "Dubailand",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "75",
      country_id: "1",
      state_id: "2",
      label: "Dubailand Residence Complex",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "76",
      country_id: "1",
      state_id: "2",
      label: "Emirates Golf Club",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "77",
      country_id: "1",
      state_id: "2",
      label: "Emirates Hills",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "78",
      country_id: "1",
      state_id: "2",
      label: "Falcon City of Wonders",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "79",
      country_id: "1",
      state_id: "2",
      label: "Green Community",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "80",
      country_id: "1",
      state_id: "2",
      label: "Greens",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "81",
      country_id: "1",
      state_id: "2",
      label: "Hacienda-Aralia",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "82",
      country_id: "1",
      state_id: "2",
      label: "Dubai Production City (IMPZ)",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "83",
      country_id: "1",
      state_id: "2",
      label: "International City",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "84",
      country_id: "1",
      state_id: "2",
      label: "Jebel Ali",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "85",
      country_id: "1",
      state_id: "2",
      label: "Jumeirah",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "86",
      country_id: "1",
      state_id: "2",
      label: "Jumeirah Beach Residence",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "87",
      country_id: "1",
      state_id: "2",
      label: "Jumeirah Golf Estates",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "88",
      country_id: "1",
      state_id: "2",
      label: "Jumeirah Heights",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "89",
      country_id: "1",
      state_id: "2",
      label: "Jumeirah Hills",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "90",
      country_id: "1",
      state_id: "2",
      label: "Jumeirah Islands",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "91",
      country_id: "1",
      state_id: "2",
      label: "Jumeirah Lake Towers",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "92",
      country_id: "1",
      state_id: "2",
      label: "Jumeirah Park",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "93",
      country_id: "1",
      state_id: "2",
      label: "Jumeirah Village Circle",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "94",
      country_id: "1",
      state_id: "2",
      label: "Jumeirah Village Triangle",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "95",
      country_id: "1",
      state_id: "2",
      label: "Living Legends",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "96",
      country_id: "1",
      state_id: "2",
      label: "Liwan",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "97",
      country_id: "1",
      state_id: "2",
      label: "Majan",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "98",
      country_id: "1",
      state_id: "2",
      label: "Meadows",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "99",
      country_id: "1",
      state_id: "2",
      label: "Meydan",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "100",
      country_id: "1",
      state_id: "2",
      label: "Meydan avenue",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "101",
      country_id: "1",
      state_id: "2",
      label: "Mina Rashid",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "102",
      country_id: "1",
      state_id: "2",
      label: "Mira Oasis",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "103",
      country_id: "1",
      state_id: "2",
      label: "Mirdif",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "104",
      country_id: "1",
      state_id: "2",
      label: "Mizin",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "105",
      country_id: "1",
      state_id: "2",
      label: "Mohammad Bin Rashid City",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "106",
      country_id: "1",
      state_id: "2",
      label: "Motor City",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "107",
      country_id: "1",
      state_id: "2",
      label: "Mudon",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "108",
      country_id: "1",
      state_id: "2",
      label: "Muhaisnah",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "109",
      country_id: "1",
      state_id: "2",
      label: "Nad Al Sheba",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "110",
      country_id: "1",
      state_id: "2",
      label: "Nadd Al Hammar",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "111",
      country_id: "1",
      state_id: "2",
      label: "Old Town",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "112",
      country_id: "1",
      state_id: "2",
      label: "Other",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "113",
      country_id: "1",
      state_id: "2",
      label: "Oud Al Muteena",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "114",
      country_id: "1",
      state_id: "2",
      label: "Oud Metha",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "115",
      country_id: "1",
      state_id: "2",
      label: "Palm Jebel Ali",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "116",
      country_id: "1",
      state_id: "2",
      label: "Palm Jumeirah",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "117",
      country_id: "1",
      state_id: "2",
      label: "Pearl Jumeirah",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "118",
      country_id: "1",
      state_id: "2",
      label: "Ras Al Khor",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "119",
      country_id: "1",
      state_id: "2",
      label: "Reem",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "120",
      country_id: "1",
      state_id: "2",
      label: "Remraam",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "121",
      country_id: "1",
      state_id: "2",
      label: "Satwa",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "122",
      country_id: "1",
      state_id: "2",
      label: "Serena",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "123",
      country_id: "1",
      state_id: "2",
      label: "Sheikh Zayed Road",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "124",
      country_id: "1",
      state_id: "2",
      label: "Silicon Oasis",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "125",
      country_id: "1",
      state_id: "2",
      label: "Dubai Sports City",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "126",
      country_id: "1",
      state_id: "2",
      label: "The Springs",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "127",
      country_id: "1",
      state_id: "2",
      label: "Technology Park",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "128",
      country_id: "1",
      state_id: "2",
      label: "Technopark",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "129",
      country_id: "1",
      state_id: "2",
      label: "The Gardens",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "130",
      country_id: "1",
      state_id: "2",
      label: "The Hills",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "131",
      country_id: "1",
      state_id: "2",
      label: "The Lakes",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "132",
      country_id: "1",
      state_id: "2",
      label: "The Ridge",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "133",
      country_id: "1",
      state_id: "2",
      label: "The Sustainable City",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "134",
      country_id: "1",
      state_id: "2",
      label: "The Valley",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "135",
      country_id: "1",
      state_id: "2",
      label: "The Views",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "136",
      country_id: "1",
      state_id: "2",
      label: "The Villa (All)",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "137",
      country_id: "1",
      state_id: "2",
      label: "The World Islands",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "138",
      country_id: "1",
      state_id: "2",
      label: "Tiger Woods",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "139",
      country_id: "1",
      state_id: "2",
      label: "Tilal Al Ghaf Development",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "140",
      country_id: "1",
      state_id: "2",
      label: "Town Square",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "141",
      country_id: "1",
      state_id: "2",
      label: "Umm Al Sheif",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "142",
      country_id: "1",
      state_id: "2",
      label: "Umm Al Sheif",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "143",
      country_id: "1",
      state_id: "2",
      label: "Umm Hurair",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "144",
      country_id: "1",
      state_id: "2",
      label: "Umm Ramool",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "145",
      country_id: "1",
      state_id: "2",
      label: "Umm Suqeim",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "146",
      country_id: "1",
      state_id: "2",
      label: "Victory Heights",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "147",
      country_id: "1",
      state_id: "2",
      label: "World Trade Centre",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "148",
      country_id: "1",
      state_id: "2",
      label: "Zabeel Road",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "149",
      country_id: "1",
      state_id: "1",
      label: "Abu Dhabi Gate City",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "150",
      country_id: "1",
      state_id: "1",
      label: "Abu Dhabi Island",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "151",
      country_id: "1",
      state_id: "1",
      label: "Airport Road",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "152",
      country_id: "1",
      state_id: "1",
      label: "Al Aman",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "153",
      country_id: "1",
      state_id: "1",
      label: "Al Aryam",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "154",
      country_id: "1",
      state_id: "1",
      label: "Al Badaa",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "155",
      country_id: "1",
      state_id: "1",
      label: "Al Bahia",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "156",
      country_id: "1",
      state_id: "1",
      label: "Al Baraha",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "157",
      country_id: "1",
      state_id: "1",
      label: "Al Bateen",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "158",
      country_id: "1",
      state_id: "1",
      label: "Al Dana",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "159",
      country_id: "1",
      state_id: "1",
      label: "Al Danah",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "160",
      country_id: "1",
      state_id: "1",
      label: "Al Danah",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "161",
      country_id: "1",
      state_id: "1",
      label: "Al Dhafrah",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "162",
      country_id: "1",
      state_id: "1",
      label: "Al Fahid Island",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "163",
      country_id: "1",
      state_id: "1",
      label: "Al Falah City",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "164",
      country_id: "1",
      state_id: "1",
      label: "Al Faya",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "165",
      country_id: "1",
      state_id: "1",
      label: "Al Ghadeer",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "166",
      country_id: "1",
      state_id: "1",
      label: "Al Gurm West",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "167",
      country_id: "1",
      state_id: "1",
      label: "Al Hosn",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "168",
      country_id: "1",
      state_id: "1",
      label: "Al Hudayriat Island",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "169",
      country_id: "1",
      state_id: "1",
      label: "Al Ittihad Road",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "170",
      country_id: "1",
      state_id: "1",
      label: "Al Karamah",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "171",
      country_id: "1",
      state_id: "1",
      label: "Al Khaleej Al Arabi Street",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "172",
      country_id: "1",
      state_id: "1",
      label: "Al Khalidiya",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "173",
      country_id: "1",
      state_id: "1",
      label: "Al Khazna",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "174",
      country_id: "1",
      state_id: "1",
      label: "Al Khubeirah",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "175",
      country_id: "1",
      state_id: "1",
      label: "Al Lissaily",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "176",
      country_id: "1",
      state_id: "1",
      label: "Al Maffraq",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "177",
      country_id: "1",
      state_id: "1",
      label: "Al Manaseer",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "178",
      country_id: "1",
      state_id: "1",
      label: "Al Manhal",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "179",
      country_id: "1",
      state_id: "1",
      label: "Al Maqtaa",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "180",
      country_id: "1",
      state_id: "1",
      label: "Al Marina",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "181",
      country_id: "1",
      state_id: "1",
      label: "Al Markaz",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "182",
      country_id: "1",
      state_id: "1",
      label: "Al Markaziyah",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "183",
      country_id: "1",
      state_id: "1",
      label: "Al Maryah Island",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "184",
      country_id: "1",
      state_id: "1",
      label: "Al Mina",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "185",
      country_id: "1",
      state_id: "1",
      label: "Al Muntazah",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "186",
      country_id: "1",
      state_id: "1",
      label: "Al Mushrif",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "187",
      country_id: "1",
      state_id: "1",
      label: "Al Nahda Abu Dhabi",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "188",
      country_id: "1",
      state_id: "1",
      label: "Al Nahyan",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "189",
      country_id: "1",
      state_id: "1",
      label: "Al Nahyan Camp",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "190",
      country_id: "1",
      state_id: "1",
      label: "Al Najda Street",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "191",
      country_id: "1",
      state_id: "1",
      label: "Al Nasr Street",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "192",
      country_id: "1",
      state_id: "1",
      label: "Al Qurm",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "193",
      country_id: "1",
      state_id: "1",
      label: "Al Raha",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "194",
      country_id: "1",
      state_id: "1",
      label: "Al Raha Beach",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "195",
      country_id: "1",
      state_id: "1",
      label: "Al Raha Gardens",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "196",
      country_id: "1",
      state_id: "1",
      label: "Al Raha Golf Gardens",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "197",
      country_id: "1",
      state_id: "1",
      label: "Al Rawdah",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "198",
      country_id: "1",
      state_id: "1",
      label: "Al Razeen",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "199",
      country_id: "1",
      state_id: "1",
      label: "Al Reef",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "200",
      country_id: "1",
      state_id: "1",
      label: "Al Reem Island",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "201",
      country_id: "1",
      state_id: "1",
      label: "Al Rehhan",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "202",
      country_id: "1",
      state_id: "1",
      label: "Al Ruwais",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "203",
      country_id: "1",
      state_id: "1",
      label: "Al Safarat District",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "204",
      country_id: "1",
      state_id: "1",
      label: "Al Samha",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "205",
      country_id: "1",
      state_id: "1",
      label: "Al Shahama",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "206",
      country_id: "1",
      state_id: "1",
      label: "Al Shaleela",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "207",
      country_id: "1",
      state_id: "1",
      label: "Al Shamkha",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "208",
      country_id: "1",
      state_id: "1",
      label: "Al Sowwah",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "209",
      country_id: "1",
      state_id: "1",
      label: "Al Taweelah",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "210",
      country_id: "1",
      state_id: "1",
      label: "Al Thurayya",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "211",
      country_id: "1",
      state_id: "1",
      label: "AL Wahda",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "212",
      country_id: "1",
      state_id: "1",
      label: "Al Wathba",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "213",
      country_id: "1",
      state_id: "1",
      label: "Al Zaab",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "214",
      country_id: "1",
      state_id: "1",
      label: "Al Zahiya",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "215",
      country_id: "1",
      state_id: "1",
      label: "Al Zahraa",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "216",
      country_id: "1",
      state_id: "1",
      label: "Arabian Village",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "217",
      country_id: "1",
      state_id: "1",
      label: "Bani Yas",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "218",
      country_id: "1",
      state_id: "1",
      label: "Between Two Bridges",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "219",
      country_id: "1",
      state_id: "1",
      label: "Building Materials City",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "220",
      country_id: "1",
      state_id: "1",
      label: "City Downtown",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "221",
      country_id: "1",
      state_id: "1",
      label: "Corniche",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "222",
      country_id: "1",
      state_id: "1",
      label: "Corniche Area",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "223",
      country_id: "1",
      state_id: "1",
      label: "Corniche Road",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "224",
      country_id: "1",
      state_id: "1",
      label: "Danet Abu Dhabi",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "225",
      country_id: "1",
      state_id: "1",
      label: "Defence Street",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "226",
      country_id: "1",
      state_id: "1",
      label: "Delma Street",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "227",
      country_id: "1",
      state_id: "1",
      label: "Desert Village",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "228",
      country_id: "1",
      state_id: "1",
      label: "Eastern Road",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "229",
      country_id: "1",
      state_id: "1",
      label: "Electra Street",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "230",
      country_id: "1",
      state_id: "1",
      label: "Ghantoot",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "231",
      country_id: "1",
      state_id: "1",
      label: "Grand Mosque District",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "232",
      country_id: "1",
      state_id: "1",
      label: "Hamdan Street",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "233",
      country_id: "1",
      state_id: "1",
      label: "Happiness Island",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "234",
      country_id: "1",
      state_id: "1",
      label: "Happiness Island",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "235",
      country_id: "1",
      state_id: "1",
      label: "Hydra Village",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "236",
      country_id: "1",
      state_id: "1",
      label: "Jawazat Street",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "237",
      country_id: "1",
      state_id: "1",
      label: "Khalidia",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "238",
      country_id: "1",
      state_id: "1",
      label: "Khalifa City (All)",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "239",
      country_id: "1",
      state_id: "1",
      label: "Khalifa city a",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "240",
      country_id: "1",
      state_id: "1",
      label: "Khalifa city b",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "241",
      country_id: "1",
      state_id: "1",
      label: "Khalifa City C",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "242",
      country_id: "1",
      state_id: "1",
      label: "Khalifa Park",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "243",
      country_id: "1",
      state_id: "1",
      label: "Khalifa Street",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "244",
      country_id: "1",
      state_id: "1",
      label: "Liwa Street",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "245",
      country_id: "1",
      state_id: "1",
      label: "Lulu Island",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "246",
      country_id: "1",
      state_id: "1",
      label: "Madinat Zayed",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "247",
      country_id: "1",
      state_id: "1",
      label: "Madinat Zayed (Western Region)",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "248",
      country_id: "1",
      state_id: "1",
      label: "Marina Village",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "249",
      country_id: "1",
      state_id: "1",
      label: "Masdar City",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "250",
      country_id: "1",
      state_id: "1",
      label: "Mbz",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "251",
      country_id: "1",
      state_id: "1",
      label: "Mohamed Bin Zayed City",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "252",
      country_id: "1",
      state_id: "1",
      label: "Muroor Area",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "253",
      country_id: "1",
      state_id: "1",
      label: "Musaffah Industrial Area",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "254",
      country_id: "1",
      state_id: "1",
      label: "Mussafah",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "255",
      country_id: "1",
      state_id: "1",
      label: "Nareel Island",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "256",
      country_id: "1",
      state_id: "1",
      label: "New Khalifa City",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "257",
      country_id: "1",
      state_id: "1",
      label: "Nurai Island",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "258",
      country_id: "1",
      state_id: "1",
      label: "Officers Club Area",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "259",
      country_id: "1",
      state_id: "1",
      label: "Saadiyat Island",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "260",
      country_id: "1",
      state_id: "1",
      label: "Salam Street",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "261",
      country_id: "1",
      state_id: "1",
      label: "Sas Al Nakhl",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "262",
      country_id: "1",
      state_id: "1",
      label: "Shakhbout City",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "263",
      country_id: "1",
      state_id: "1",
      label: "Sheikh Zayed Bin Sultan St.",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "264",
      country_id: "1",
      state_id: "1",
      label: "Tourist Club Area",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "265",
      country_id: "1",
      state_id: "1",
      label: "Yas Island",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "266",
      country_id: "1",
      state_id: "1",
      label: "Zayed City",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "267",
      country_id: "1",
      state_id: "1",
      label: "Zayed Military City",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "268",
      country_id: "1",
      state_id: "1",
      label: "Zayed Sports City",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "269",
      country_id: "1",
      state_id: "3",
      label: "Abu Shagara",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "270",
      country_id: "1",
      state_id: "3",
      label: "Al Azra",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "271",
      country_id: "1",
      state_id: "3",
      label: "Al Badie",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "272",
      country_id: "1",
      state_id: "3",
      label: "Al Barashi",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "273",
      country_id: "1",
      state_id: "3",
      label: "Al Butina",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "274",
      country_id: "1",
      state_id: "3",
      label: "Al Dhaid",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "275",
      country_id: "1",
      state_id: "3",
      label: "Al Ettihad Street",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "276",
      country_id: "1",
      state_id: "3",
      label: "Al Faisht",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "277",
      country_id: "1",
      state_id: "3",
      label: "Al Falaj",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "278",
      country_id: "1",
      state_id: "3",
      label: "Al Fayha",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "279",
      country_id: "1",
      state_id: "3",
      label: "Al Fisht",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "280",
      country_id: "1",
      state_id: "3",
      label: "Al Garayen",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "281",
      country_id: "1",
      state_id: "3",
      label: "Al Ghafeyah Area",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "282",
      country_id: "1",
      state_id: "3",
      label: "Al Gharayen",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "283",
      country_id: "1",
      state_id: "3",
      label: "Al Gharb",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "284",
      country_id: "1",
      state_id: "3",
      label: "Al Ghuair",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "285",
      country_id: "1",
      state_id: "3",
      label: "Al Ghubaiba",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "286",
      country_id: "1",
      state_id: "3",
      label: "Al Goaz",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "287",
      country_id: "1",
      state_id: "3",
      label: "Al Gulayaa",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "288",
      country_id: "1",
      state_id: "3",
      label: "Al Hamriya",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "289",
      country_id: "1",
      state_id: "3",
      label: "AL Hazannah",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "290",
      country_id: "1",
      state_id: "3",
      label: "Al Heerah",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "291",
      country_id: "1",
      state_id: "3",
      label: "Al Jada",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "292",
      country_id: "1",
      state_id: "3",
      label: "Al Jubail",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "293",
      country_id: "1",
      state_id: "3",
      label: "Al Khaldeia Area",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "294",
      country_id: "1",
      state_id: "3",
      label: "Al Khan",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "295",
      country_id: "1",
      state_id: "3",
      label: "Al Khezamia",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "296",
      country_id: "1",
      state_id: "3",
      label: "Al Majaz",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "297",
      country_id: "1",
      state_id: "3",
      label: "Al Mamzar - Sharjah",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "298",
      country_id: "1",
      state_id: "3",
      label: "Al Mansoura",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "299",
      country_id: "1",
      state_id: "3",
      label: "Al Mareija",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "300",
      country_id: "1",
      state_id: "3",
      label: "Al Mirgab",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "301",
      country_id: "1",
      state_id: "3",
      label: "Al Mujarrah",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "302",
      country_id: "1",
      state_id: "3",
      label: "Al Nabaah",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "303",
      country_id: "1",
      state_id: "3",
      label: "Al Nahda-Sharjah",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "304",
      country_id: "1",
      state_id: "3",
      label: "Al Naimiya Area",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "305",
      country_id: "1",
      state_id: "3",
      label: "Al Naseriya",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "306",
      country_id: "1",
      state_id: "3",
      label: "Al Nekhailat",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "307",
      country_id: "1",
      state_id: "3",
      label: "Al Nouf",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "308",
      country_id: "1",
      state_id: "3",
      label: "Al Nujoom Islands",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "309",
      country_id: "1",
      state_id: "3",
      label: "Al Qarain",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "310",
      country_id: "1",
      state_id: "3",
      label: "Al Qasbaa",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "311",
      country_id: "1",
      state_id: "3",
      label: "Al Qasimia",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "312",
      country_id: "1",
      state_id: "3",
      label: "Al Qulayaah",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "313",
      country_id: "1",
      state_id: "3",
      label: "Al Rahmaniya",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "314",
      country_id: "1",
      state_id: "3",
      label: "Al Ramla",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "315",
      country_id: "1",
      state_id: "3",
      label: "Al Ramtha",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "316",
      country_id: "1",
      state_id: "3",
      label: "Al Rifaah",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "317",
      country_id: "1",
      state_id: "3",
      label: "Al Riffa Area",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "318",
      country_id: "1",
      state_id: "3",
      label: "Al Riqqa",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "319",
      country_id: "1",
      state_id: "3",
      label: "Al Sajaa",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "320",
      country_id: "1",
      state_id: "3",
      label: "Al Shahba",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "321",
      country_id: "1",
      state_id: "3",
      label: "Al Sharq",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "322",
      country_id: "1",
      state_id: "3",
      label: "Al Shuwaihean",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "323",
      country_id: "1",
      state_id: "3",
      label: "Al Suyoh 1",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "324",
      country_id: "1",
      state_id: "3",
      label: "Al Suyoh 10",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "325",
      country_id: "1",
      state_id: "3",
      label: "Al Suyoh 11",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "326",
      country_id: "1",
      state_id: "3",
      label: "Al Suyoh 12",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "327",
      country_id: "1",
      state_id: "3",
      label: "Al Suyoh 13",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "328",
      country_id: "1",
      state_id: "3",
      label: "Al Suyoh 14",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "329",
      country_id: "1",
      state_id: "3",
      label: "Al Suyoh 15",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "330",
      country_id: "1",
      state_id: "3",
      label: "Al Suyoh 16",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "331",
      country_id: "1",
      state_id: "3",
      label: "Al Suyoh 17",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "332",
      country_id: "1",
      state_id: "3",
      label: "Al Suyoh 18",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "333",
      country_id: "1",
      state_id: "3",
      label: "Al Suyoh 19",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "334",
      country_id: "1",
      state_id: "3",
      label: "Al Suyoh 2",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "335",
      country_id: "1",
      state_id: "3",
      label: "Al Suyoh 20",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "336",
      country_id: "1",
      state_id: "3",
      label: "Al Suyoh 3",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "337",
      country_id: "1",
      state_id: "3",
      label: "Al Suyoh 4",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "338",
      country_id: "1",
      state_id: "3",
      label: "Al Suyoh 5",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "339",
      country_id: "1",
      state_id: "3",
      label: "Al Suyoh 6",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "340",
      country_id: "1",
      state_id: "3",
      label: "Al Suyoh 7",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "341",
      country_id: "1",
      state_id: "3",
      label: "Al Suyoh 8",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "342",
      country_id: "1",
      state_id: "3",
      label: "Al Suyoh 8",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "343",
      country_id: "1",
      state_id: "3",
      label: "Al Suyoh 9",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "344",
      country_id: "1",
      state_id: "3",
      label: "Al Taawun",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "345",
      country_id: "1",
      state_id: "3",
      label: "Al Tai",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "346",
      country_id: "1",
      state_id: "3",
      label: "Al Wahda",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "347",
      country_id: "1",
      state_id: "3",
      label: "Al Zubair",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "348",
      country_id: "1",
      state_id: "3",
      label: "Corniche Al Buhaira",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "349",
      country_id: "1",
      state_id: "3",
      label: "Halwan",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "350",
      country_id: "1",
      state_id: "3",
      label: "Hamriyah Free Zone",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "351",
      country_id: "1",
      state_id: "3",
      label: "Hooshi",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "352",
      country_id: "1",
      state_id: "3",
      label: "Juwaiza",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "353",
      country_id: "1",
      state_id: "3",
      label: "Maleha",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "354",
      country_id: "1",
      state_id: "3",
      label: "Maryam Island",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "355",
      country_id: "1",
      state_id: "3",
      label: "Maysaloon",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "356",
      country_id: "1",
      state_id: "3",
      label: "Muelih",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "357",
      country_id: "1",
      state_id: "3",
      label: "Muwaileh",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "358",
      country_id: "1",
      state_id: "3",
      label: "Muwaileh Commercial",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "359",
      country_id: "1",
      state_id: "3",
      label: "Rolla Area",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "360",
      country_id: "1",
      state_id: "3",
      label: "Sharjah Airport Freezone (Saif)",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "361",
      country_id: "1",
      state_id: "3",
      label: "Sharjah Industrial Area",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "362",
      country_id: "1",
      state_id: "3",
      label: "Um Altaraffa",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "363",
      country_id: "1",
      state_id: "3",
      label: "Umm Khanoor",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "364",
      country_id: "1",
      state_id: "3",
      label: "Wasit",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "365",
      country_id: "1",
      state_id: "3",
      label: "Wusha",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "366",
      country_id: "1",
      state_id: "4",
      label: "Ain Ajman",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "367",
      country_id: "1",
      state_id: "4",
      label: "Ajman Boulevard",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "368",
      country_id: "1",
      state_id: "4",
      label: "Ajman Corniche Road",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "369",
      country_id: "1",
      state_id: "4",
      label: "Ajman Downtown",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "370",
      country_id: "1",
      state_id: "4",
      label: "Ajman Global City",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "371",
      country_id: "1",
      state_id: "4",
      label: "Ajman Hills",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "372",
      country_id: "1",
      state_id: "4",
      label: "Ajman Industrial Area",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "373",
      country_id: "1",
      state_id: "4",
      label: "Ajman Marina",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "374",
      country_id: "1",
      state_id: "4",
      label: "Ajman Meadows",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "375",
      country_id: "1",
      state_id: "4",
      label: "Ajman Uptown",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "376",
      country_id: "1",
      state_id: "4",
      label: "Al Ameera Village",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "377",
      country_id: "1",
      state_id: "4",
      label: "Al Bustan",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "378",
      country_id: "1",
      state_id: "4",
      label: "Al Helio 2",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "379",
      country_id: "1",
      state_id: "4",
      label: "Al Humaid City",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "380",
      country_id: "1",
      state_id: "4",
      label: "Al Ittihad Village",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "381",
      country_id: "1",
      state_id: "4",
      label: "Al Jurf",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "382",
      country_id: "1",
      state_id: "4",
      label: "Al mwaihat",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "383",
      country_id: "1",
      state_id: "4",
      label: "Al Nabghah",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "384",
      country_id: "1",
      state_id: "4",
      label: "Al Naemiyah",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "385",
      country_id: "1",
      state_id: "4",
      label: "Al Nuaimia 1",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "386",
      country_id: "1",
      state_id: "4",
      label: "Al Nuaimia 2",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "387",
      country_id: "1",
      state_id: "4",
      label: "Al Raqaib",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "388",
      country_id: "1",
      state_id: "4",
      label: "Al Rashidiya",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "389",
      country_id: "1",
      state_id: "4",
      label: "Al Rawda",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "390",
      country_id: "1",
      state_id: "4",
      label: "Al Rawda ",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "391",
      country_id: "1",
      state_id: "4",
      label: "Al Rumaila",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "392",
      country_id: "1",
      state_id: "4",
      label: "Al Yasmeen",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "393",
      country_id: "1",
      state_id: "4",
      label: "Al Zahraa",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "394",
      country_id: "1",
      state_id: "4",
      label: "Awali City",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "395",
      country_id: "1",
      state_id: "4",
      label: "Corniche Ajman",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "396",
      country_id: "1",
      state_id: "4",
      label: "Emirates City",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "397",
      country_id: "1",
      state_id: "4",
      label: "Garden City",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "398",
      country_id: "1",
      state_id: "4",
      label: "Green City",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "399",
      country_id: "1",
      state_id: "4",
      label: "Manama",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "400",
      country_id: "1",
      state_id: "4",
      label: "Marmooka City",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "401",
      country_id: "1",
      state_id: "4",
      label: "Musheiref",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "402",
      country_id: "1",
      state_id: "4",
      label: "New Industrial Area",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "403",
      country_id: "1",
      state_id: "4",
      label: "Park View City",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "404",
      country_id: "1",
      state_id: "4",
      label: "Sheikh Khalifa Bin Zayed",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "405",
      country_id: "1",
      state_id: "5",
      label: "Al Salam City",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "406",
      country_id: "1",
      state_id: "5",
      label: "Al Salamah",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "407",
      country_id: "1",
      state_id: "5",
      label: "Amwaj Resort",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "408",
      country_id: "1",
      state_id: "5",
      label: "Emirates Modern Industrial",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "409",
      country_id: "1",
      state_id: "5",
      label: "Etihad Road",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "410",
      country_id: "1",
      state_id: "5",
      label: "Falaj Al Moalla",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "411",
      country_id: "1",
      state_id: "5",
      label: "Khor Al Beidah",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "412",
      country_id: "1",
      state_id: "5",
      label: "Umm Al Quwain",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "413",
      country_id: "1",
      state_id: "5",
      label: "Umm Al Quwain Marina",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "414",
      country_id: "1",
      state_id: "5",
      label: "White Bay",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "415",
      country_id: "1",
      state_id: "6",
      label: "Al Ghail",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "416",
      country_id: "1",
      state_id: "6",
      label: "Al Hamra (All)",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "417",
      country_id: "1",
      state_id: "6",
      label: "Al Hamra Village",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "418",
      country_id: "1",
      state_id: "6",
      label: "Al Hudaibah",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "419",
      country_id: "1",
      state_id: "6",
      label: "Al Jazirah Al Hamra",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "420",
      country_id: "1",
      state_id: "6",
      label: "Al Mairid",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "421",
      country_id: "1",
      state_id: "6",
      label: "Al Marjan Island",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "422",
      country_id: "1",
      state_id: "6",
      label: "Al Nakheel",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "423",
      country_id: "1",
      state_id: "6",
      label: "Al Qusaidat",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "424",
      country_id: "1",
      state_id: "6",
      label: "Al Riffa",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "425",
      country_id: "1",
      state_id: "6",
      label: "Al Seer",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "426",
      country_id: "1",
      state_id: "6",
      label: "Bab al bahr",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "427",
      country_id: "1",
      state_id: "6",
      label: "Cornich Ras Al Khaima",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "428",
      country_id: "1",
      state_id: "6",
      label: "Corniche Ras Al Khaimah",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "429",
      country_id: "1",
      state_id: "6",
      label: "Cove",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "430",
      country_id: "1",
      state_id: "6",
      label: "Cove Rotana",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "431",
      country_id: "1",
      state_id: "6",
      label: "Dana Island",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "432",
      country_id: "1",
      state_id: "6",
      label: "Golf Apartments",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "433",
      country_id: "1",
      state_id: "6",
      label: "Granada",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "434",
      country_id: "1",
      state_id: "6",
      label: "Julfar",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "435",
      country_id: "1",
      state_id: "6",
      label: "Julfar Office",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "436",
      country_id: "1",
      state_id: "6",
      label: "Julfar Residential",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "437",
      country_id: "1",
      state_id: "6",
      label: "Khuzam",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "438",
      country_id: "1",
      state_id: "6",
      label: "Luxury B Villa",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "439",
      country_id: "1",
      state_id: "6",
      label: "Luxury C Villa",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "440",
      country_id: "1",
      state_id: "6",
      label: "Malibu",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "441",
      country_id: "1",
      state_id: "6",
      label: "Marina Apartments",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "442",
      country_id: "1",
      state_id: "6",
      label: "Mina Al Arab",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "443",
      country_id: "1",
      state_id: "6",
      label: "Oceana Apartments",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "444",
      country_id: "1",
      state_id: "6",
      label: "Rak Financial City",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "445",
      country_id: "1",
      state_id: "6",
      label: "Rak Industrial And Technology Park",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "446",
      country_id: "1",
      state_id: "6",
      label: "Ras Al Khaimah Creek",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "447",
      country_id: "1",
      state_id: "6",
      label: "Ras Al Khaimah Gateway",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "448",
      country_id: "1",
      state_id: "6",
      label: "Ras Al Khaimah Waterfront",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "449",
      country_id: "1",
      state_id: "6",
      label: "Royal Breeze Villas",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "450",
      country_id: "1",
      state_id: "6",
      label: "Saraya Islands",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "451",
      country_id: "1",
      state_id: "6",
      label: "Seih Al Burairat",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "452",
      country_id: "1",
      state_id: "6",
      label: "Sheikh Muhammad Bin Salem Road",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "453",
      country_id: "1",
      state_id: "6",
      label: "Yasmin Village",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "454",
      country_id: "1",
      state_id: "7",
      label: "Al Aqah",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "455",
      country_id: "1",
      state_id: "7",
      label: "Corniche Al Fujairah",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "456",
      country_id: "1",
      state_id: "7",
      label: "Diba Al Fujairah",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "457",
      country_id: "1",
      state_id: "7",
      label: "Downtown Fujairah",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "458",
      country_id: "1",
      state_id: "7",
      label: "Sharm",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "459",
      country_id: "1",
      state_id: "7",
      label: "Sheikh Hamad Bin Abdullah St",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "460",
      country_id: "1",
      state_id: "2",
      label: "The Lagoons",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "461",
      country_id: "1",
      state_id: "2",
      label: "DAMAC Hills (Akoya by DAMAC)",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "462",
      country_id: "1",
      state_id: "2",
      label: "The Greens",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "463",
      country_id: "1",
      state_id: "2",
      label: "Jumeirah Village Circle (JVC)",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "464",
      country_id: "1",
      state_id: "2",
      label: "Dubai South",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "465",
      country_id: "1",
      state_id: "2",
      label: "Barsha Heights (Tecom)",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "466",
      country_id: "1",
      state_id: "2",
      label: "Jumeirah Beach Residence (JBR)",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "467",
      country_id: "1",
      state_id: "2",
      label: "Mohammed Bin Rashid City",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "468",
      country_id: "1",
      state_id: "2",
      label: "Jumeirah Lake Towers (JLT)",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "469",
      country_id: "1",
      state_id: "2",
      label: "Meydan City",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "470",
      country_id: "1",
      state_id: "2",
      label: "Dubai Silicon Oasis",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "471",
      country_id: "1",
      state_id: "2",
      label: "Aljada",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "472",
      country_id: "1",
      state_id: "2",
      label: "Jumeirah Golf Estate",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "473",
      country_id: "1",
      state_id: "2",
      label: "DAMAC Hills 2 (Akoya Oxygen)",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "474",
      country_id: "1",
      state_id: "2",
      label: "Tilal Al Ghaf",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "475",
      country_id: "1",
      state_id: "2",
      label: "The Villa",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "476",
      country_id: "1",
      state_id: "2",
      label: "Jumeirah Village Triangle (JVT)",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "477",
      country_id: "1",
      state_id: "2",
      label: "Emaar South",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "478",
      country_id: "1",
      state_id: "2",
      label: "Dubai Residence Complex",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "479",
      country_id: "1",
      state_id: "2",
      label: "Dubai Industrial Park",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "480",
      country_id: "1",
      state_id: "2",
      label: "DAMAC Hills 2 (Akoya by DAMAC)",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "481",
      country_id: "1",
      state_id: "2",
      label: "DAMAC Hills",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "482",
      country_id: "1",
      state_id: "2",
      label: "Damac Lagoons",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "483",
      country_id: "1",
      state_id: "2",
      label: "Wasl Gate",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "484",
      country_id: "1",
      state_id: "2",
      label: "Golf City",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "485",
      country_id: "1",
      state_id: "2",
      label: "Za'abeel",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "486",
      country_id: "1",
      state_id: "2",
      label: "Dubai Investment Park (DIP)",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "488",
      country_id: "1",
      state_id: "2",
      label: "Sobha Hartland",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
    {
      value: "489",
      country_id: "1",
      state_id: "2",
      label: "Khalifa City",
      location_geo_lat: "",
      location_geo_long: "",
      location_status: "1",
    },
  ];
}
